#### ❇️ Tensors 

Tensors are data structures similar to arrays and matrices wjich are use to encode inputs, outputs and parameters of models <br>
Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators

In [1]:
import torch
import numpy as np

#### Initializing a Tensor

In [2]:
# Directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
# From a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# With random or constant values:
shape=(2, 2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2710, 0.9181],
        [0.0190, 0.6447]]) 

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.]])


#### Moving tensors to GPU

By default tensors are created on CPU We need to explicitly move tensors to the GPU using .to method

In [5]:
# We move our tensor to the GPU if available
tensor = torch.rand(2, 3)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

#### Attributes of a Tensor

In [6]:
tensor = torch.rand(2, 3)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Tensor is stored on: cpu


#### Operations on Tensors


In [7]:
# Standard indexing and slicing just like NumPy
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
# Arithmetic Ops
# This computes the matrix multiplication between two tensors.
y1 = tensor.matmul(tensor.T)

# This computes the element-wise product.
z1 = tensor * tensor

In [9]:
# Converting single value tensors to a Python 
# Numerical value
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [10]:
# Inplace Ops
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


#### Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.



In [11]:
t = torch.ones(5)
print(f"tensor: {t}")
n = t.numpy()
print(f"numpy array: {n}")

tensor: tensor([1., 1., 1., 1., 1.])
numpy array: [1. 1. 1. 1. 1.]


In [12]:
t.add_(1)
print(f"tensor: {t}")
print(f"numpy array: {n}")

tensor: tensor([2., 2., 2., 2., 2.])
numpy array: [2. 2. 2. 2. 2.]
